// packages/generator/src/artifacts/solid-jsx/jsx.ts
import { ArtifactFile } from '../artifact-map'

export const solidJsxFactoryArtifact = new ArtifactFile({
  id: 'jsx/factory.js',
  fileName: 'factory',
  type: 'js',
  dir: (ctx) => ctx.paths.jsx,
  dependencies: ['jsxFactory', 'jsxFramework'],
  imports: {
    'jsx/factory-helper.js': [
      'composeCvaFn',
      'composeShouldForwardProps',
      'defaultShouldForwardProp',
      'getDisplayName',
    ],
    'helpers.js': ['normalizeHTMLProps'],
    'css/index.js': ['css', 'cx', 'cva'],
    'jsx/is-valid-prop.js': ['isCssProperty'],
  },
  computed(ctx) {
    return { jsx: ctx.jsx }
  },
  code(params) {
    const { componentName, factoryName } = params.computed.jsx

    return `
    import { createMemo, mergeProps, splitProps } from 'solid-js'
    import { Dynamic, createComponent } from 'solid-js/web'

    function styledFn(element, configOrCva = {}, options = {}) {
      const cvaFn =
        configOrCva.__cva__ || configOrCva.__recipe__
          ? configOrCva
          : cva(configOrCva)

      const forwardFn = options.shouldForwardProp || defaultShouldForwardProp
      const shouldForwardProp = (prop) => forwardFn(prop, cvaFn.variantKeys)

      const defaultProps = Object.assign(
        options.dataAttr && configOrCva.__name__
          ? { 'data-recipe': configOrCva.__name__ }
          : {},
        options.defaultProps
      )

      const __cvaFn__ = composeCvaFn(element.__cva__, cvaFn)
      const __shouldForwardProps__ = composeShouldForwardProps(
        element,
        shouldForwardProp
      )

      const ${componentName} = (props) => {
        const mergedProps = mergeProps(
          { as: element.__base__ || element },
          defaultProps,
          props
        )

        const [localProps, restProps] = splitProps(mergedProps, [
          'as',
          'class',
          'className',
        ])

        const [htmlProps, aProps] = splitProps(restProps, normalizeHTMLProps.keys)

        const forwardedKeys = createMemo(() => {
          const keys = Object.keys(aProps)
          return keys.filter((prop) => __shouldForwardProps__(prop))
        })

        const [forwardedProps, variantProps, bProps] = splitProps(aProps, forwardedKeys(), __cvaFn__.variantKeys)

        const cssPropKeys = createMemo(() => {
          const keys = Object.keys(bProps)
          return keys.filter((prop) => isCssProperty(prop))
        })

        const [styleProps, elementProps] = splitProps(bProps, cssPropKeys())

        function recipeClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const compoundVariantStyles =
            __cvaFn__.__getCompoundVariantCss__?.(variantProps)
          return cx(
            __cvaFn__(variantProps, false),
            css(compoundVariantStyles, propStyles, cssStyles),
            localProps.class,
            localProps.className
          )
        }

        function cvaClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const cvaStyles = __cvaFn__.raw(variantProps)
          return cx(
            css(cvaStyles, propStyles, cssStyles),
            localProps.class,
            localProps.className
          )
        }

        const classes = configOrCva.__recipe__ ? recipeClass : cvaClass

        if (forwardedProps.className) {
          delete forwardedProps.className
        }

        return createComponent(
          Dynamic,
          mergeProps(forwardedProps, elementProps, normalizeHTMLProps(htmlProps), {
            get component() {
              return localProps.as
            },
            get class() {
              return classes()
            },
          })
        )
      }

      const name = getDisplayName(element)

      ${componentName}.displayName = \`${factoryName}.\${name}\`
      ${componentName}.__cva__ = __cvaFn__
      ${componentName}.__base__ = element
      ${componentName}.__shouldForwardProps__ = shouldForwardProp

      return ${componentName}
    }

    function createJsxFactory() {
      const cache = new Map()

      return new Proxy(styledFn, {
        apply(_, __, args) {
          return styledFn(...args)
        },
        get(_, el) {
          if (!cache.has(el)) {
            cache.set(el, styledFn(el))
          }
          return cache.get(el)
        },
      })
    }

    export const ${factoryName} = /* @__PURE__ */ createJsxFactory()
    `
  },
})

// packages/generator/src/artifacts/react-jsx/jsx.ts
import { ArtifactFile } from '../artifact'

export const reactJsxFactoryArtifact = new ArtifactFile({
  id: 'jsx/factory.js',
  fileName: 'factory',
  type: 'js',
  dir: (ctx) => ctx.paths.jsx,
  dependencies: ['jsxFactory', 'jsxFramework'],
  imports: {
    'css/index.js': ['css', 'cx', 'cva'],
    'helpers.js': ['splitProps', 'normalizeHTMLProps'],
    'jsx/factory-helper.js': [
      'defaultShouldForwardProp',
      'composeShouldForwardProps',
      'composeCvaFn',
      'getDisplayName',
    ],
    'jsx/is-valid-prop.js': ['isCssProperty'],
  },
  computed(ctx) {
    return { jsx: ctx.jsx }
  },
  code(params) {
    const { componentName, factoryName } = params.computed.jsx

    return `
    import { createElement, forwardRef, useMemo } from 'react'

    function styledFn(Dynamic, configOrCva = {}, options = {}) {
      const cvaFn = configOrCva.__cva__ || configOrCva.__recipe__ ? configOrCva : cva(configOrCva)

      const forwardFn = options.shouldForwardProp || defaultShouldForwardProp
      const shouldForwardProp = (prop) => forwardFn(prop, cvaFn.variantKeys)

      const defaultProps = Object.assign(
        options.dataAttr && configOrCva.__name__ ? { 'data-recipe': configOrCva.__name__ } : {},
        options.defaultProps,
      )

      const __cvaFn__ = composeCvaFn(Dynamic.__cva__, cvaFn)
      const __shouldForwardProps__ = composeShouldForwardProps(Dynamic, shouldForwardProp)
      const __base__ = Dynamic.__base__ || Dynamic

      const ${componentName} = /* @__PURE__ */ forwardRef(function ${componentName}(props, ref) {
        const { as: Element = __base__, children, ...restProps } = props

        const combinedProps = useMemo(() => Object.assign({}, defaultProps, restProps), [restProps])

        const [htmlProps, forwardedProps, variantProps, styleProps, elementProps] = useMemo(() => {
          return splitProps(combinedProps, normalizeHTMLProps.keys, __shouldForwardProps__, __cvaFn__.variantKeys, isCssProperty)
        }, [combinedProps])

        function recipeClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const compoundVariantStyles = __cvaFn__.__getCompoundVariantCss__?.(variantProps)
          return cx(__cvaFn__(variantProps, false), css(compoundVariantStyles, propStyles, cssStyles), combinedProps.className)
        }

        function cvaClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const cvaStyles = __cvaFn__.raw(variantProps)
          return cx(css(cvaStyles, propStyles, cssStyles), combinedProps.className)
        }

        const classes = configOrCva.__recipe__ ? recipeClass : cvaClass

        return createElement(Element, {
          ref,
          ...forwardedProps,
          ...elementProps,
          ...normalizeHTMLProps(htmlProps),
          className: classes(),
        }, combinedProps.children ?? children)
      })

      const name = getDisplayName(__base__)

      ${componentName}.displayName = \`${factoryName}.\${name}\`
      ${componentName}.__cva__ = __cvaFn__
      ${componentName}.__base__ = __base__
      ${componentName}.__shouldForwardProps__ = shouldForwardProp

      return ${componentName}
    }

    function createJsxFactory() {
      const cache = new Map()

      return new Proxy(styledFn, {
        apply(_, __, args) {
          return styledFn(...args)
        },
        get(_, el) {
          if (!cache.has(el)) {
            cache.set(el, styledFn(el))
          }
          return cache.get(el)
        },
      })
    }

    export const ${factoryName} = /* @__PURE__ */ createJsxFactory()
    `
  },
})
